Implement a plugin for Stratis
snapshotmanager/snapm pull request #72
Opened 2024-07-11 17:20 UTC by bmr-cymru

2024-07-15 19:58 UTC, bmr-cymru commented
Expecting the tests to fail on this push... Need to build and install Stratis in the test workflow.

2024-09-27 14:28 UTC, mulkieran requested changes

2024-09-27 14:28 UTC, mulkieran commented on snapm/manager/plugins/stratislib/_introspect.py
> +      <arg name="key_fd" type="(bh)" direction="in" />
Remove this entry.

2024-09-27 18:07 UTC, mulkieran requested changes
One tiny thing...

2024-11-25 13:27 UTC, merged